---
  - hosts: webserver
    become: yes
    tasks:
       - name: Restarting required services
         service:
            name: "{{ item }}"
            state: restarted

         loop:
          - sshd
          - apache2 
          - cron

