---
 - name: Setting up webserver using APACHE
   hosts: webserver
   become: yes
   tasks:
     - name: Installing Apache webserver package on Debian family node
       apt: 
          name: apache2 
          state: present 
          update_cache: yes
       when: ansible_os_family == "Debian" or ansible_memtotal_mb >= 5000

     - name: Installing Apache webserver package on RedHat family node
       yum:  
          name: httpd 
          state: present
       when: ansible_os_family=="RedHat"

     - name: Start the Webserver by validating apache2 service
       service:
          name: apache2
          state: started
          enabled: yes
       when: ansible_os_family=="Debian"

     - name: Start the webserver by validating HTTPD service
       service:
          name: httpd
          state: started
          enabled: yes
       when: ansible_os_family=="RedHat"

     - name: Placing webserver to document root
       copy: 
          src: /home/labsuser/webpage.html
          dest: /var/www/html/index.html
 
