---
 - hosts: mygroup
   become: yes
   vars:
           - http_port: 8081
           - document_root: /var/www/html
   tasks: 
     - name: Install Apache Webserver 
       apt:
          name: apache2
          state: present
          update_cache: yes
       notify: "Restart Apache2 service"   

     - name: Apache Listen on port {{http_port}}
       template: 
          src: httpPort.j2
          dest: /etc/apache2/ports.conf
       notify: "Restart Apache2 service"   

     - name: Apache port {{http_port}} update in configuration file
       template: 
          src: httpConf.j2
          dest: /etc/apache2/sites-enabled/000-default.conf
       notify: "Restart Apache2 service"   

     - name: Copying Webpage
       copy:
          src: webpageindex.html
          dest: "{{document_root}}/index.html"

   handlers:
     - name: "Restart Apache2 service"
       service:
          name: apache2
          state: restarted
          enabled: true
