---
 - name: Installing and configuring Apache Webserver
   hosts: webserver
   become: yes
   ignore_errors: yes                     ## this ignore errors is for all tasks  from this play
   vars: 
     - package1: apache5                     ### intentionally package name is wrong to generate error
     - service1: apache2
   tasks:
     - name: "Installing {{ package1 }}"
       apt: 
          name: "{{ package1 }}"
          state: present
          #       ignore_errors: yes                      ### this ignore errors is only for one task

     - name: "Restart service {{service1 }}"
       service:
          name: "{{ service1 }}"
          state: restarted
